### ISSUE TITLE
Allow Editor to be published

### ISSUE THREAD

**Issue by kolbyd** [winnipegfir/CZWG-core#1]
![image](https://user-images.githubusercontent.com/58011171/83334647-eaa86800-a275-11ea-92c5-14b18c6796c1.png)

Allow the editor to be published and change it from 'Gander Oceanic Staff' to 'Winnipeg FIR Staff'

**Comment by CaptainWhite95** [comment]
Has been updated to Winnipeg FIR Staff. Issue closed
