### ISSUE TITLE
Homepage Metadata

### ISSUE THREAD

**Issue by natopower** [winnipegfir/CZWG-core#11]
Make it say "Welcome to Winnipeg - located in the heart of Canada on the VATSIM network." Something like that, anyway.

![image](https://user-images.githubusercontent.com/29666499/94998918-f4c3d580-058b-11eb-801d-ee9fb866ee34.png)

**Comment by kolbyd** [comment]
Done with aa36aacd760d499e41267b1b6e0cd3032dbf17e5. Need to make sure every public page has a description.

**Comment by kolbyd** [comment]
Every page that needs one has a description. 5a5b6bdea5c8060acaf6af41a6f151bab15a5ef2
