### ISSUE TITLE
Homepage: Make splash with submitted photos

### ISSUE THREAD

**Issue by natopower** [winnipegfir/CZWG-core#19]
Have pilots/controllers submit screenshots every month for a chance to be featured on the front page. Turn the "rotation" images code to make it work for this, if easy. Would need to have a "credit: ______"

**Comment by kolbyd** [comment]
Completed with aa36aacd760d499e41267b1b6e0cd3032dbf17e5 and ec8ccb4a2fc9f71d5c923eb7a6b706915d3dcfba. For right now, can only be submitted by admins.
