### ISSUE TITLE
Update Controller Applications to suit Winnipeg FIR needs.

### ISSUE THREAD

**Issue by CaptainWhite95** [winnipegfir/CZWG-core#2]
- [x] -> Add control position requested to Application.
- [x] -> User Dashboard view of events controller has applied to
- [x] -> User Dashboard view of events a controller is confirmed a time slot and position for.
- [ ] -> Ability for the Events Coordinator to move a controller from "Applied" to "Confirmed".

**Comment by kolbyd** [comment]
#1f66dd20869794d68e26b736d7c2ddf0b590d0b9f

**Comment by kolbyd** [comment]
#f66dd20869794d68e26b736d7c2ddf0b590d0b9f

**Comment by kolbyd** [comment]
#f66dd20869794d68e26b736d7c2ddf0b590d0b9f

**Comment by kolbyd** [comment]
f66dd20869794d68e26b736d7c2ddf0b590d0b9f

**Comment by kolbyd** [comment]
f66dd20869794d68e26b736d7c2ddf0b590d0b9f

**Comment by CaptainWhite95** [comment]
60a4390e3c80842b75e4b4ba64ce5a60ee01703a

**Comment by natopower** [comment]
This has been completed.
