### ISSUE TITLE
Training Page

### ISSUE THREAD

**Issue by natopower** [winnipegfir/CZWG-core#21]
IDEA: Add Training page for students who are considering joining. This outlines how training works, and includes a waitlist so students know how long they'll be waiting. Either pull a number from trello or have the CI update this number regularly with an estimate.

**Comment by CaptainWhite95** [comment]
One suggestion for waitlist is to use the Controller Training system to add users to the waitlist on the site and pull that number

**Comment by natopower** [comment]
Done with 0a4be77bcb23f28a8c42ff6a9d973e9fc773b20d
