### ISSUE TITLE
Monitored Positions editing

### ISSUE THREAD

**Issue by kolbyd** [winnipegfir/CZWG-core#3]
![image](https://user-images.githubusercontent.com/58011171/83341488-19dcca80-a2b2-11ea-9365-4da943533f36.png)

Make them dropdown work and make the dropdown show up as it would be used (so Staff Only would say 'no' if it isn't staff only)

**Comment by CaptainWhite95** [comment]
93f01737b6a22ab0b6f235e0aeb9770f740ff14d
Removed as this functionality is not needed for our FIR operations. Set default value of staffOnly column inside monitored_positions table to 0.
