### ISSUE TITLE
Make Ticket replies civilised 

### ISSUE THREAD

**Issue by kolbyd** [winnipegfir/CZWG-core#4]
![image](https://user-images.githubusercontent.com/58011171/83344168-34726c00-a2d1-11ea-8e79-ddb04d3dc59e.png)
just... not this.

**paragraph ~~is~~ will be approved as requested**

**Comment by CaptainWhite95** [comment]
No fix is needed. aaaaaaaaaaaaaaaaaa.... is one full word and will not wordbreak. No such ticket is logical, and normal words will wordbreak and stay within the container.
