### ISSUE TITLE
Required tasks for site launch

### ISSUE THREAD

**Issue by CaptainWhite95** [winnipegfir/CZWG-core#9]
- [x] Ticket system message bug, see Issue # 2
- [x] Add all FIR data - News, Events, SOP’s, Policies, Phraseology
- [x] Finish events system in user dashboard, see Issue # 4
- [x] Discord System
- [x] Add audits for critical Edit/Delete
- [x] Open Staff Tickets on Dashboard
- [x] Restructure directories so Staff/Admin items in correct directories, organize routes page
- [x] Confirm all permissions and what they can view are correct
- [x] Mail

**Comment by CaptainWhite95** [comment]
Open staff tickets on dashboard completed. 5b9c6f2108a631bfc7217cde175876ab201ce5a3

**Comment by CaptainWhite95** [comment]
Ticket replies resolved. See Issue # 4

**Comment by natopower** [comment]
All SOPs, Policies and FIR Data are now on the new site.

**Comment by kolbyd** [comment]
Mail is done. We have moved to Sendgrid for our mail.

**Comment by kolbyd** [comment]
Done. With release v1.0.
